GET http://localhost:8080

###
GET http://localhost:8080/user

###
POST http://localhost:8080/user
Content-Type: application/json

{
    "account": "client02"
}
###

GET http://localhost:8200/intake/v2/events