receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  debug:
service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]